pkp/pkp-lib#6685 Add tombstonemanager for OPS
pkp/ops pull request #170
Opened 2021-08-08 19:07 UTC by ajnyga

https://github.com/pkp/pkp-lib/issues/6685

2021-08-09 21:05 UTC, asmecher requested changes
Thanks, @ajnyga! I made some comments on the PR.

2021-08-09 21:05 UTC, asmecher commented on classes/submission/Repository.inc.php
> +            $preprintTombstoneManager = new \PreprintTombstoneManager();
It should be possible to use a fully qualified classname (`use APP\preprint\PreprintTombstoneManager;`) and then remove the `import` call.

2021-08-10 09:12 UTC, ajnyga commented on classes/preprint/PreprintTombstoneManager.inc.php
> +    public function insertPreprintTombstone(&$preprint, &$context)
are these not needed for the hook there?

2021-08-10 09:13 UTC, ajnyga commented on classes/preprint/PreprintTombstoneManager.inc.php
> +        $OAISetObjectsIds = [
check

2021-08-10 09:13 UTC, ajnyga commented on classes/preprint/PreprintTombstoneManager.inc.php
> +if (!PKP_STRICT_MODE) {
check

2021-08-10 09:16 UTC, ajnyga commented on classes/submission/Repository.inc.php
> +            $preprintTombstoneManager = new \PreprintTombstoneManager();
check

2021-08-15 14:46 UTC, ajnyga commented on classes/preprint/PreprintTombstoneManager.inc.php
> +    public function insertPreprintTombstone(&$preprint, &$context)
I think the only plugin I have seen using the hook was the old openaire plugin. I will remove the references, but note that OJS still has those in the same code.

2021-08-16 21:21 UTC, asmecher commented on classes/preprint/PreprintTombstoneManager.inc.php
> +    public function insertPreprintTombstone(&$preprint, &$context)
Thanks! I've removed the references from the OJS code.

2021-08-16 21:22 UTC, merged

2021-08-16 21:22 UTC, asmecher commented
Merged -- thanks, @ajnyga!