[OPS] #6850 Repository Pattern for Author Entity
pkp/ops pull request #172
Opened 2021-08-13 07:44 UTC by defstat

2021-08-17 09:52 UTC, NateWr requested changes
:+1:  just a few comments

2021-08-17 09:52 UTC, NateWr commented on classes/author/Repository.inc.php
> +}
This is not needed. You can add the pkp-lib Repository to the `Repo` facade in pkp-lib and that should be enough.

2021-08-17 09:52 UTC, NateWr commented on classes/facades/Repo.inc.php
> +    }
See comment above.

2021-08-17 09:52 UTC, NateWr commented on pages/search/SearchHandler.inc.php
> +
This is another place where you need to rewrite from using the iterator to using the collection. Here's what this would look like for all of the code here and the array maps below it:

```php
$submissions = Repo::author
    ->getMany(...)
    ->map(function($author) {
        return $author->getData('publicationId');
    })
    ->unique()
    ->map(function($publicationId) {
        return Repo::publication()->get($publicationId)->getData('submissionId');
    })
    ->unique()
    ->map(function($submissionId) {
        return Repo::submission()->get($submissionId);
    });
```

2021-08-17 23:42 UTC, asmecher commented on plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
> -        // Create a mocked AuthorDAO that returns our test author.
Rather than removing the test, fix it to mock using Mockery; see https://github.com/pkp/pkp-lib/pull/7170/files#diff-25d473c51d8999687f6c5973520cbf1d398a6cff069377558a092c0149c811a0R357 for an example.

2021-08-19 14:12 UTC, defstat commented on plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
> -        // Create a mocked AuthorDAO that returns our test author.
(the same applies to OJS)

the code was the following:

```
import('classes.article.AuthorDAO');
$authorDao = $this->getMockBuilder(AuthorDAO::class)
    ->setMethods(['getBySubmissionId'])
    ->getMock();
$authorDao->expects($this->any())
    ->method('getBySubmissionId')
    ->will($this->returnValue([$author]));
DAORegistry::registerDAO('AuthorDAO', $authorDao);
```
I suppose that this code mocks a `getBySubmissionId` method for the `AuthorDAO` DAO and defined that the return value for that would be the test `$author` object.

I could not find any reference to `getBySubmissionId` for any authorDAO reference, though, concluding that it could be unused code. Am I missing something here?

2021-08-19 15:26 UTC, defstat commented on classes/author/Repository.inc.php
> +}
Removed

2021-08-19 15:27 UTC, defstat commented on classes/facades/Repo.inc.php
> +    }
Removed

2021-08-19 15:28 UTC, defstat commented on pages/search/SearchHandler.inc.php
> +
Fixed

2021-08-19 17:19 UTC, asmecher commented on plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
> -        // Create a mocked AuthorDAO that returns our test author.
Ah! I just noticed that the entire test is skipped:
https://github.com/pkp/ops/pull/172/files#diff-b3771d977a6130c893408a95a8eab762ada7cce8b1befed50200e7ca8a4beb96L55

I would recommend just adding a FIXME here about `getBySubmissionId` needing to be adapted to `getByPublicationId` (for the 3.3 upgrade) and `AuthorDAO` needing to be adapted to the new namespaced version. But don't fix it now -- this may well get rewritten when we overhaul unit testing.

2021-08-20 07:40 UTC, defstat commented on plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
> -        // Create a mocked AuthorDAO that returns our test author.
FIXME Added (also in OJS)

2021-08-30 20:25 UTC, asmecher commented on plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
> -        // Create a mocked AuthorDAO that returns our test author.
(It looks like the code was removed from OJS but a FIXME was not added -- crosslinking https://github.com/pkp/ojs/pull/3167/files#r698782387)

2021-08-30 20:25 UTC, asmecher commented on tests/classes/search/PreprintSearchIndexTest.php
> -        // Mock an preprint so that the authors are not
(FIXME needed here: https://github.com/pkp/ops/pull/172/files#r692335653)

2021-09-02 08:27 UTC, defstat commented on plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
> -        // Create a mocked AuthorDAO that returns our test author.
Added

2021-09-02 08:27 UTC, defstat commented on tests/classes/search/PreprintSearchIndexTest.php
> -        // Mock an preprint so that the authors are not
Fixed

2021-09-15 01:37 UTC, asmecher commented
Cherry-picked in manually due to merge conflict.

2021-09-15 01:37 UTC, closed without merging