pkp/pkp-lib#7126 Refactor to galley repository and move to pkp-lib
pkp/ops pull request #260
Opened 2022-04-06 09:56 UTC by NateWr

2022-04-06 10:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/ops?pullRequest=260) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/ops?pullRequest=260) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/ops?pullRequest=260) it.</sub>

2022-04-07 01:48 UTC, asmecher requested changes
Just a few comments! I see some good incidental clean-up here too.

2022-04-07 01:48 UTC, asmecher commented on classes/author/Author.inc.php
> +    class_alias('\APP\author\Author', '\Author');
Is this for the filter framework (the way classes are named in the persisted filter configs)? I did think about adding a migration for this but wanted to leave it for the moment and come back to it once namespacing is better established and we're interested in removing the compatibility stuff. In any case this is fine.

2022-04-07 01:48 UTC, asmecher commented on classes/submission/Submission.inc.php
>       * @deprecated 3.2.0.0
This is a pretty old deprecated function -- is it widely used? (also below)

2022-04-07 01:48 UTC, asmecher commented on classes/submission/Submission.inc.php
> +            )->toArray()
I *think* `$publication->getData('authors')` was allowed to remain a Collection. It would be good to pick an approach and stick with it.

2022-04-07 01:48 UTC, asmecher commented on controllers/grid/preprintGalleys/PreprintGalleyGridHandler.inc.php
>          return $galleys;
I don't recall the grid stuff working with `LazyCollections`; this might need to be turned into an associative array.

2022-04-07 01:48 UTC, asmecher commented on tests/classes/search/PreprintSearchIndexTest.php
> +        // FIXME: GalleyDAO::getBySubmissionId returns iterator; array expected here. Fix expectations.
(Did you intend to fix the FIXME, or leave this for later?)

2022-04-07 01:58 UTC, asmecher commented on tests/classes/search/PreprintSearchIndexTest.php
> +        // FIXME: GalleyDAO::getBySubmissionId returns iterator; array expected here. Fix expectations.
Whoops, I see this was just migrated from another repo.

2022-04-07 11:02 UTC, NateWr commented on classes/author/Author.inc.php
> +    class_alias('\APP\author\Author', '\Author');
Yeah, I was running into fatal errors with the import/export toolset not finding the class somewhere in the filters. I'm not sure why it didn't effect the import/export before, though...

2022-04-07 11:04 UTC, NateWr commented on classes/submission/Submission.inc.php
>       * @deprecated 3.2.0.0
It was widely used in templates, so we've hung on to it for a little while longer. It's not used by us any more. Remove it and other `getLocalizedCoverImageXXXX()` methods?

2022-04-07 11:07 UTC, NateWr commented on classes/submission/Submission.inc.php
> +            )->toArray()
This function only exists for backwards-compatibility, so I thought it best to stay consistent with the original type. It was deprecated in 3.2.0.0, but _very_ widely used across themes and plugins.

Should I file an issue to review the deprecated tags from 3.2 or 3.3? I don't necessarily want to roll it into these PRs.

2022-04-07 11:11 UTC, NateWr commented on controllers/grid/preprintGalleys/PreprintGalleyGridHandler.inc.php
>          return $galleys;
I think you solved that here:

https://github.com/pkp/pkp-lib/blob/584eea97fb386b6f6492e13badcc674391272e0a/classes/controllers/grid/GridHandler.inc.php#L394-L401

2022-04-07 21:40 UTC, asmecher commented on controllers/grid/preprintGalleys/PreprintGalleyGridHandler.inc.php
>          return $galleys;
...and promptly forgot about it :)

2022-04-07 21:42 UTC, asmecher commented on classes/submission/Submission.inc.php
> +            )->toArray()
OK, makes sense to me. No, don't bother filing a general issue for clean-up, it should be part of the dev cycle in general.

2022-04-07 21:43 UTC, asmecher commented on classes/submission/Submission.inc.php
>       * @deprecated 3.2.0.0
Yes please!

2022-04-11 17:40 UTC, merged