pkp/pkp-lib#8027 OPS preprints should support DOI versioning
pkp/ops pull request #314
Opened 2022-07-24 17:29 UTC by ewhanson

2022-07-27 15:37 UTC, asmecher commented on classes/doi/Repository.inc.php
> +        return match ($pubObjectType) {
:+1: I've been unreasonably excited about `match` and am looking forward to replacing some really ugly formulations with it!

2022-10-17 09:48 UTC, NateWr requested changes

2022-10-17 09:48 UTC, NateWr commented on classes/components/forms/context/DoiSetupSettingsForm.php
> +                        'label' => __('common.no')
I prefer option labels that offer more confirmation about what is being selected, like:

> - [ ] Yes, assign a unique DOI to every version of a preprint.
> - [ ] No, all versions of a preprint should have the same DOI.

2022-10-17 09:48 UTC, NateWr commented on schemas/context.json
> +			"default": true
Can you add a "description" to this that says what it does? (This filters through to the REST API docs.)

2022-11-10 14:16 UTC, bozana commented on api/v1/_dois/BackendDoiHandler.php
> -
Here too: Maybe to get the submission here already and check if it belongs to the context?

2022-11-10 14:17 UTC, bozana reviewed
I haven't taken a deeper look at the test. Will do it as soon as possible...

2023-01-24 14:50 UTC, bozana commented on templates/frontend/objects/preprint_details.tpl
> +
Maybe we do not need this check now that we save DOIs for all publications even if the versioning is off?

2023-01-27 22:51 UTC, ewhanson commented on templates/frontend/objects/preprint_details.tpl
> +
Good idea. That way we can get it directly from the publication without worrying about whether it's the current publication or not.

2023-01-30 15:51 UTC, merged