[OPS][stable-3_3_0] #5697 Enable edit galley, display the form disabled
pkp/ops pull request #347
Opened 2022-09-06 06:39 UTC by defstat

2022-09-28 13:46 UTC, NateWr commented
You need to add the submodule commit here too.

2022-10-05 11:18 UTC, NateWr requested changes

2022-10-05 11:18 UTC, NateWr commented on plugins/pubIds/doi/templates/doiSuffixEdit.tpl
> +				{/if}
Same comment here as in OJS.

2022-10-13 06:16 UTC, defstat commented on plugins/pubIds/doi/templates/doiSuffixEdit.tpl
> +				{/if}
Changed

2022-10-18 19:50 UTC, merged