Feature/main/8700 improve slow query
pkp/ops pull request #511
Opened 2023-04-07 12:30 UTC by jonasraoni

2024-05-27 19:39 UTC, asmecher requested changes

2024-05-27 19:39 UTC, asmecher commented on classes/author/DAO.php
> +        $baseSql = '
This function should be removed entirely (as has already been done from OJS). It's an oversight that it was left here.

2024-05-28 11:04 UTC, jonasraoni commented on classes/author/DAO.php
> +        $baseSql = '
Ok!

2024-05-30 19:08 UTC, merged

2024-05-30 19:20 UTC, jonasraoni commented
Closing this one, I fixed a couple of unrelated bugs and converted the affected queries to the Laravel Query.