pkp/pkp-lib#6057 Refactor submission files
pkp/ops pull request #73
Opened 2020-10-29 15:51 UTC by NateWr

2020-10-29 15:52 UTC, NateWr commented
@asmecher here ihe OPS PR. It should be pretty straightforward, but another set of eyes would be appreciated.

2020-10-29 20:02 UTC, asmecher requested changes
Looks good, Nate! Just a couple of comments.

2020-10-29 20:02 UTC, asmecher commented on classes/services/SubmissionFileService.inc.php
> +		$allowedFileStages = &$args[0];
(Prefer `$a =& $b` to `$a = &$b` for readability/consistency.)

2020-11-02 11:59 UTC, NateWr commented on classes/migration/upgrade/OPSv3_3_0UpgradeMigration.inc.php
> +			$table->foreign('submission_file_id')->references('submission_file_id')->on('submission_files');
I have run the upgrades with these and had to adjust the order in which foreign keys were applied. And it seems to work with file deletions after moving the order of deleted objects around a bit. So I _think_ these are working ok but this is something that should get identified during testing.

2020-11-13 10:12 UTC, merged