[OPS] #6490 Native Import/Export Plugin Improvements
pkp/ops pull request #98
Opened 2020-12-16 18:07 UTC by defstat

2021-01-13 20:24 UTC, asmecher requested changes
This needs some general cleanup for OJS-specific content etc.

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/filter/ArticleGalleyNativeXmlFilter.inc.php
> +	function __construct($filterGroup) {
Dead code; this function can be removed.

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/filter/ArticleGalleyNativeXmlFilter.inc.php
> +	function __construct($filterGroup) {
(Also elsewhere)

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/filter/NativeFilterHelper.inc.php
> +	function createIssueIdentificationNode($filter, $doc, $issue) {
This code shouldn't appear in OPS. In fact, pretty much all of these functions.

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
> +		return 'insertObject';
Do any of the other apps implement this differently? If not, the function should be removed.

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/locale/ar_IQ/locale.po
> +"\timport [xmlFileName] [journal_path] [user_name] ...\n"
References to `journal_path` should be adapted for OPS. (Also other OJS-specific language.) OPS still has a lot of references to `article` / `journal` in the code, and those will need to be changed, but when introducing new locale keys they should be adapted right away to avoid propagating bad translations.

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/locale/pt_BR/locale.po
> +msgid "plugins.importexport.native.import.error.issueIdentificationDuplicate"
Keys like this aren't relevant to OPS and should be removed.

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/native.xsd
> +	<element name="issues">
Issue-related content should be removed from the OPS code.

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/native.xsd
> +		<attribute name="journal_id" type="int" use="optional" />
`journal_id` should be adapted for OPS (also elsewhere)

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/templates/resultsExport.tpl
> +{if array_key_exists('errors', $errorsAndWarnings) && $errorsAndWarnings.errors|@count > 0}
As elsewhere -- escape template vars, reconcile duplicated code

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/templates/resultsImport.tpl
> +{if array_key_exists('errors', $errorsAndWarnings) && $errorsAndWarnings.errors|@count > 0}
(as elsewhere)

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> + * @brief Test native OJS export.
OPS

2021-01-13 20:24 UTC, asmecher commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> +			'/issue/id[@type="doi"]' => '10.1234/t.v1i1',
Contains issue-related content; does this pass?

2021-01-15 13:14 UTC, defstat commented on plugins/importexport/native/filter/ArticleGalleyNativeXmlFilter.inc.php
> +	function __construct($filterGroup) {
Fixed

2021-01-15 14:25 UTC, defstat commented on plugins/importexport/native/templates/resultsExport.tpl
> +{if array_key_exists('errors', $errorsAndWarnings) && $errorsAndWarnings.errors|@count > 0}
Templates moved to lib/pkp/templates/plugins/importexport/native and a common innerResults.tpl template is added for the specific block

2021-01-15 14:25 UTC, defstat commented on plugins/importexport/native/templates/resultsImport.tpl
> +{if array_key_exists('errors', $errorsAndWarnings) && $errorsAndWarnings.errors|@count > 0}
Templates moved to lib/pkp/templates/plugins/importexport/native and a common innerResults.tpl template is added for the specific block

2021-01-15 14:26 UTC, defstat commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> +			'/issue/id[@type="doi"]' => '10.1234/t.v1i1',
I removed those test for now. Is that ok?

2021-01-15 14:26 UTC, defstat commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> + * @brief Test native OJS export.
I removed those test for now. Is that ok?

2021-01-15 16:37 UTC, defstat commented on plugins/importexport/native/filter/NativeFilterHelper.inc.php
> +	function createIssueIdentificationNode($filter, $doc, $issue) {
Fixed - `PKPNativeFilterHelper` added to `lib/pkp`. `NativeFilterHelper` remained only in OJS

2021-01-15 16:40 UTC, defstat commented on plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
> +		return 'insertObject';
Removed (from OJS too)

2021-01-15 16:41 UTC, defstat commented on plugins/importexport/native/locale/ar_IQ/locale.po
> +"\timport [xmlFileName] [journal_path] [user_name] ...\n"
Tried to remove them from OPS (mainly en_US translation)

2021-01-15 16:41 UTC, defstat commented on plugins/importexport/native/native.xsd
> +	<element name="issues">
Removed

2021-01-15 16:44 UTC, defstat commented on plugins/importexport/native/native.xsd
> +		<attribute name="journal_id" type="int" use="optional" />
Removed

2021-01-15 18:12 UTC, asmecher commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> +			'/issue/id[@type="doi"]' => '10.1234/t.v1i1',
Presumably this is from the OJS codebase; can you check whether it's running there?

2021-01-15 18:12 UTC, asmecher commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> + * @brief Test native OJS export.
Same as: https://github.com/pkp/ops/pull/98#discussion_r558483925

2021-01-15 23:11 UTC, asmecher commented on plugins/importexport/native/filter/NativeXmlPreprintGalleyFilter.inc.php
> +	function _processFileRef($node, $deployment, $representation) {
I think this is dead code, both in OJS and OPS?

2021-01-15 23:13 UTC, asmecher commented on plugins/importexport/native/filter/PublicationNativeXmlFilter.inc.php
> +		$isPublished = $entity->getData('status') === STATUS_PUBLISHED;
I'd prefer for readability:
```
if ($entity->getData('status') === STATUS_PUBLISHED) {
    $entityNode->setAttribute('seq', (int) $entity->getData('seq'));
    $entityNode->setAttribute('access_status', $entity->getData('accessStatus'));
} else {
    $entityNode->setAttribute('seq', '0');
    $entityNode->setAttribute('access_status', '0');
}
```

2021-01-15 23:17 UTC, asmecher commented on plugins/importexport/native/locale/ar_IQ/locale.po
> +"\timport [xmlFileName] [journal_path] [user_name] ...\n"
I think it would be best to either remove the non-English translations entirely, or at least mark all their contents fuzzy; otherwise there's no way translators will know that these files need adaptation to match the English version.

2021-01-15 23:18 UTC, asmecher commented on plugins/importexport/native/native.xsd
> +							<restriction base="string">
Some of these stages don't apply to OPS.

2021-01-17 20:29 UTC, defstat commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> +			'/issue/id[@type="doi"]' => '10.1234/t.v1i1',
If the `lib/pkp/tools/runAllTests.sh` script is running on travis then they should run (because of `find plugins -name tests -maxdepth 3 -type d -exec $phpunit $DEBUG $TEST_CONF2 -v "{}" ";"`)

2021-01-17 20:43 UTC, defstat commented on plugins/importexport/native/filter/NativeXmlPreprintGalleyFilter.inc.php
> +	function _processFileRef($node, $deployment, $representation) {
Removed.

2021-01-17 21:11 UTC, defstat commented on plugins/importexport/native/filter/PublicationNativeXmlFilter.inc.php
> +		$isPublished = $entity->getData('status') === STATUS_PUBLISHED;
changed the syntax and moved to pkp-lib

2021-01-17 21:18 UTC, defstat commented on plugins/importexport/native/native.xsd
> +							<restriction base="string">
Because of `https://github.com/pkp/ops/blob/master/classes/core/Application.inc.php#L166` only the `Production` stage is defined.

2021-01-17 21:43 UTC, defstat commented on plugins/importexport/native/locale/ar_IQ/locale.po
> +"\timport [xmlFileName] [journal_path] [user_name] ...\n"
I think I fixed it.

2021-01-18 22:19 UTC, asmecher commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> +			'/issue/id[@type="doi"]' => '10.1234/t.v1i1',
The tests appear to be broken -- running them locally:
```
bash lib/pkp/tools/runAllTests.sh -p
```
...results in...
```
Fatal error: require_once(): Failed opening required './lib/pkp/tests/WebTestCase.inc.php' (include_path='.:/usr/share/php') in /home/asmecher/git/ojs/lib/pkp/tests/phpunit-bootstrap.php on line 125
```
Could you remove both:
- plugins/importexport/quickSubmit/tests/functional/QuickSubmitFunctionalTest.php, and
- plugins/importexport/native/tests/functional/FunctionalNativeImportTestCase.php
These are actually dead code and will give a false sense of security.

Also, the command `find plugins -name tests -maxdepth 3 -type d -exec $phpunit $DEBUG $TEST_CONF2 -v "{}" ";"` generates a warning:
```
find: warning: you have specified the global option -maxdepth after the argument -name, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
```
This might explain why those tests weren't getting executed. I'll fix that one.

2021-01-18 22:20 UTC, asmecher commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> +			'/issue/id[@type="doi"]' => '10.1234/t.v1i1',
(Also, I suspect the other contents of `plugins/importexport/native/tests/functional` are also dead)

2021-01-19 08:33 UTC, defstat commented on plugins/importexport/native/tests/functional/FunctionalNativeExportTestCase.php
> +			'/issue/id[@type="doi"]' => '10.1234/t.v1i1',
Removed the tests

2021-01-21 20:51 UTC, asmecher requested changes

2021-01-21 20:51 UTC, asmecher commented on plugins/importexport/native/README.md
> +Sample XML can be found in https://github.com/pkp/ojs/blob/[tag]/cypress/fixtures/export-issues.xml,
References to OJS.

2021-01-21 20:51 UTC, asmecher commented on plugins/importexport/native/locale/ca_ES/locale.po
> +"\tissue_id [issueId] section_id [sectionId]\n"
Issue-related elements should be removed.

2021-01-21 20:51 UTC, asmecher commented on plugins/importexport/native/locale/ar_IQ/locale.po
> +"\timport [xmlFileName] [journal_path] [user_name] ...\n"
I don't see any changes here... There are also lots of translations added via this PR for locales that don't exist in OPS at the moment. I think the amount of OJS content in translations that's being added here should really be cut way back, as lots of it will never be used, and will doubtlessly contain a lot of OJS-specific content.

2021-01-21 20:51 UTC, asmecher commented
Added some more comments, thanks. There also appear to be a bunch of submodule updates in this PR -- are those accidental?

2021-01-27 17:45 UTC, defstat commented on plugins/importexport/native/README.md
> +Sample XML can be found in https://github.com/pkp/ojs/blob/[tag]/cypress/fixtures/export-issues.xml,
Removed

2021-01-27 20:37 UTC, defstat commented
Yes the submodules where accidental

2021-01-27 20:45 UTC, defstat commented on plugins/importexport/native/README.md
> +Sample XML can be found in https://github.com/pkp/ojs/blob/[tag]/cypress/fixtures/export-issues.xml,
Removed

2021-01-27 20:46 UTC, defstat commented on plugins/importexport/native/locale/ca_ES/locale.po
> +"\tissue_id [issueId] section_id [sectionId]\n"
Have put a `#, fuzzy` directive above all `plugins.importexport.native.cliUsage` keys

2021-01-27 20:46 UTC, defstat commented on plugins/importexport/native/locale/ar_IQ/locale.po
> +"\timport [xmlFileName] [journal_path] [user_name] ...\n"
Have put a #, fuzzy directive above all plugins.importexport.native.cliUsage keys

2021-02-26 17:47 UTC, asmecher commented on plugins/importexport/native/NativeImportExportDeployment.inc.php
> +	// Deploymenturation items for subclasses to override
"Deployment" rather than "Deploymenturation". But not a big deal!

2021-02-26 17:47 UTC, asmecher commented on plugins/importexport/native/NativeImportExportDeployment.inc.php
> + * Copyright (c) 2014-2020 Simon Fraser University
For new code, use 2021 end dates.

2021-02-26 17:50 UTC, asmecher commented on plugins/importexport/native/locale/da_DK/locale.po
> +msgstr "Udvælg artikler til eksport"
This looks like OJS-specific language (articles rather than submissions); maybe flag these fuzzy? I know there's only so much you can do without a babelfish.

2021-02-26 17:50 UTC, asmecher commented on plugins/importexport/native/locale/da_DK/locale.po
> +"{$ scriptName} {$ pluginName} importere [xmlFileName] [journal_path] "
I'm not sure where the spaces came from `{$ pluginName}` but these will be broken because of them.

2021-02-26 17:51 UTC, asmecher commented on plugins/importexport/native/locale/fr_CA/locale.po
> +"d’OJS."
References OJS -- mark fuzzy.

2021-02-26 17:51 UTC, asmecher commented on plugins/importexport/native/locale/fr_CA/locale.po
> +msgstr "Plugiciel XML natif d'OJS"
References OJS -- mark fuzzy. (Also probably elsewhere.)

2021-02-26 17:53 UTC, asmecher commented
Thanks, @defstat, I've added a few trivial comments here but otherwise it's ready to go. However, please coordinate with @ajnyga -- he's got a big PR almost ready for merge that'll rename some code-based terminology that was OJS-specific in the OPS codebase. One of you will probably have to rebase around the other, and it probably makes sense for Antti-Jussi's work to go in first if it's ready.

2021-03-17 15:02 UTC, defstat commented on plugins/importexport/native/NativeImportExportDeployment.inc.php
> + * Copyright (c) 2014-2020 Simon Fraser University
Fixed - also the line bellow that - also elsewhere

2021-03-17 15:03 UTC, defstat commented on plugins/importexport/native/NativeImportExportDeployment.inc.php
> +	// Deploymenturation items for subclasses to override
fixed

2021-03-17 15:07 UTC, defstat commented on plugins/importexport/native/locale/da_DK/locale.po
> +msgstr "Udvælg artikler til eksport"
added that `#, fuzzy` directive

2021-03-17 15:09 UTC, defstat commented on plugins/importexport/native/locale/da_DK/locale.po
> +"{$ scriptName} {$ pluginName} importere [xmlFileName] [journal_path] "
me neither - Fixed the 5 occurrences for  {$ scriptName} and {$ pluginName}

2021-03-17 15:13 UTC, defstat commented on plugins/importexport/native/locale/fr_CA/locale.po
> +"d’OJS."
Added the `#, fuzzy` directive to `plugins.importexport.native.description`

2021-03-17 15:18 UTC, defstat commented on plugins/importexport/native/locale/fr_CA/locale.po
> +msgstr "Plugiciel XML natif d'OJS"
Added the `#, fuzzy` directive to `plugins.importexport.native.displayName`

2021-05-06 16:49 UTC, closed without merging